%%
net.layers = { } ;
net.layers{end+1} = struct(...
  'name', 'conv1', ...
  'type', 'conv', ...
  'weights', {{randn(1,2,1,L1,'single'), []}}, ...
  'pad', 0, ...
  'stride', 1, ...
  'learningRate', [1 1], ...
  'weightDecay', [1 0]) ;
net.layers{end+1} = struct(...
  'name', 'relu1', ...
  'type', 'relu') ;
net.layers{end+1} = struct(...
  'name', 'output (conv2)', ...
  'type', 'conv', ...
  'weights', {{randn(1,2,1,L2,'single'), []}}, ...
  'pad', 0, ...
  'stride', 1, ...
  'learningRate', [1 1], ...
  'weightDecay', [1 0]) ;
net = vl_simplenn_tidy(net) ; % Consolidate the network, fixing any missing option
%%
res = vl_simplenn(net, x ) ;