clc;clear;clc;clear;
%% prepare Data
X_train = randn(1,24,1,1000);
x = X_train(:,:,:,1);
%%
L1 = 1;
L2 = 1;
%% Forward Pass
%
w1 = rand(1,2,1,L1);
%b1 = rand(L1,1);
b1 = [];
z1 = vl_nnconv(x,w1,b1) ;
a1 = vl_nnrelu(z1);
%
w2 = rand(1,1,1,L2);
%b1 = rand(L2,1);
b2 = [];
z2 = vl_nnconv(a1,w2,b2);
%%
net.layers = { } ;
net.layers{end+1} = struct(...
  'name', 'conv1', ...
  'type', 'conv', ...
  'weights', {{randn(1,2,1,L1,'single'), []}}, ...
  'pad', 0, ...
  'stride', 1, ...
  'learningRate', [1 1], ...
  'weightDecay', [1 0]) ;
net.layers{end+1} = struct(...
  'name', 'relu1', ...
  'type', 'relu') ;
net.layers{end+1} = struct(...
  'name', 'output (conv2)', ...
  'type', 'conv', ...
  'weights', {{randn(1,2,1,L2,'single'), []}}, ...
  'pad', 0, ...
  'stride', 1, ...
  'learningRate', [1 1], ...
  'weightDecay', [1 0]) ;
net = vl_simplenn_tidy(net) ; % Consolidate the network, fixing any missing option
%%
res = vl_simplenn(net, x ) ;