clc;clear;clc;clear;
%%
X_train = randn(1,1,1,1000);
x = X_train(:,:,:,1);
lambda = 0;
%%
L1 = 3;
L2 = 3;
%%
net.layers = { } ;
net.layers{end+1} = struct(...
  'name', 'conv1', ...
  'type', 'conv', ...
  'weights', {{randn(1,1,1,L1,'single'), randn(L1,1,'single')}}, ...
  'pad', 0, ...
  'stride', 1, ...
  'learningRate', [1 1], ...
  'weightDecay', [1 0]) ;
net.layers{end+1} = struct(...
  'name', 'relu1', ...
  'type', 'relu') ;
net.layers{end+1} = struct(...
  'name', 'output (conv2)', ...
  'type', 'conv', ...
  'weights', {{randn(1,1,1,L2,'single'), randn(1,1,'single')}}, ...
  'pad', 0, ...
  'stride', 1, ...
  'learningRate', [1 1], ...
  'weightDecay', [1 0]) ;
net.layers{end+1} = struct(...
  'name', 'L2 Loss', ...
  'type', 'pdist', ...
  'p', 2, ...
  'epsilon', lambda) ;
net = vl_simplenn_tidy(net) ; % Consolidate the network, fixing any missing option
%%
res = vl_simplenn(net, X_train(:,:,:,1) ) ;
